[project]
name = "desktop-app"
version = "0.1.0"
description = "Desktop application for WattWatch"
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "pyside6>=6.8.2.1",
    "pytest>=8.3.4",
    "requests>=2.32.3",
]
